### ISSUE TITLE
Cover for the Knomi V2

### ISSUE THREAD

**Issue by CBoismenu** [bigtreetech/HBB#1]
Hi,

Looking at the Voron 2.4 350 skirt part for the KNOMO V2 and it seems to be missing the retaining bracket that would secure the KNOMI V2 to the skirt.

Also the holes for the threaded inserts that are used to secure the bottom cover are to small or not formed all the way for both Skirt Items.

**Comment by BTTJUSTIN** [comment]
Thanks for reporting. We will investigate this further get the documentation updated if needed and close this issue out once the updates are uploaded.

**Comment by CBoismenu** [comment]
Thank you.

**Comment by BTTJUSTIN** [comment]
The documentation has been updated. （HBB_PRINT_PARTS/VORON SKIRT 350/KNOMI2-Mounting支架.STL）
Thanks again for  pointing out the issue
